trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# Install dependencies and build
- script: |
    npm ci
    npm run build
  displayName: 'Install dependencies and build'

# Archive the standalone build
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.next/standalone'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive standalone build'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'VShareAppPCon'  # Your service connection
    appName: 'VibeShare' # Your main Web App name
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'