trigger:
  branches:
    include:
      - main   # adjust to your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'
  appName: 'JoShotVibeShare'             # Your Azure Web App name
  azureSubscription: 'VibeShare-ARM-Connection'  # Your service connection name

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Install and Build'
    steps:
    # Use Node 18
    - task: UseNode@1
      inputs:
        versionSpec: '$(node_version)'

    # Print debug info
    - script: |
        echo "Current directory: $(pwd)"
        node -v
        npm -v
      displayName: 'Debug Node & NPM versions'

    # Install dependencies & build
    - script: |
        npm ci
        npm run build
      displayName: 'Install dependencies & build Next.js'

    # Archive standalone build
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '.next/standalone'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
      displayName: 'Archive standalone build'

    # Publish artifact for deployment
    - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifact: drop
      displayName: 'Publish build artifact'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Azure Web App'
    environment: 'AzureWebApp'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
            displayName: 'Deploy to Azure Web App'